name: Build action

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build stage1 packages
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo ::set-output name=date::$(date -u +%Y%m%d)
          echo ::set-output name=epoch::$(date -u +%s)
        shell: bash

      - uses: actions/checkout@v3
      - run: echo "${{ secrets.MELANGE_RSA }}" > /tmp/melange.rsa
      - run: sudo cp ./melange.rsa.pub /etc/apk/keys/melange.rsa.pub

      - uses: chainguard-dev/actions/setup-melange@main

      - uses: chainguard-dev/actions/inky-build-pkg@main
        with:
          package-name: cross-binutils
          signing-key-path: /tmp/melange.rsa

      - uses: chainguard-dev/actions/inky-build-pkg@main
        with:
          package-name: cross-gcc
          signing-key-path: /tmp/melange.rsa

      - uses: chainguard-dev/actions/inky-build-pkg@main
        with:
          package-name: cross-linux-headers
          signing-key-path: /tmp/melange.rsa

      - uses: chainguard-dev/actions/inky-build-pkg@main
        with:
          package-name: cross-glibc
          signing-key-path: /tmp/melange.rsa

      - uses: chainguard-dev/actions/inky-build-pkg@main
        with:
          package-name: cross-libstdc++
          signing-key-path: /tmp/melange.rsa

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/567187841907/locations/global/workloadIdentityPools/staging-shared-9bd2/providers/staging-shared-gha"
          service_account: "staging-images-ci@staging-images-183e.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: staging-images-183e

      - name: 'Check that GCloud is properly configured'
        run: |
          gcloud info

      - name: 'Upload the repository to a bucket'
        run: |
          cp /etc/apk/keys/melange.rsa.pub ${{ github.workspace }}/packages/melange.rsa.pub
          # TODO: remove this comment after the validation test
          # gcloud --quiet alpha storage cp --recursive ${{ github.workspace }}/packages/ gs://wolfi-registry-source/bootstrap/stage1/
          gcloud --quiet alpha storage cp --recursive ${{ github.workspace }}/packages/ gs://test-cpanato/bootstrap/stage1/
